---
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: /tmp/facts_cache
      fact_caching_timeout: 7200
  env:
    ANSIBLE_ROLES_PATH: ~/.cache/molecule/ansible-role-nginx/${MOLECULE_SCENARIO_NAME}/roles:${MOLECULE_PROJECT_DIRECTORY}/..:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
