---
- name: (Alpine Linux) Set up signing key
  when: ansible_facts['os_family'] == 'Alpine'
  block:
    - name: (Alpine Linux) Set up NGINX signing key URL
      ansible.builtin.set_fact:
        keysite: "{{ nginx_signing_key | default(nginx_default_signing_key_rsa_pub) }}"

    - name: (Alpine Linux) Download NGINX signing key
      ansible.builtin.get_url:
        url: "{{ keysite }}"
        dest: /etc/apk/keys/nginx_signing.rsa.pub
        mode: "0400"

- name: (Debian/Red Hat/SLES OSs) Set up NGINX signing key URL
  ansible.builtin.set_fact:
    keysite: "{{ nginx_signing_key | default(nginx_default_signing_key_pgp) }}"
  when: ansible_facts['os_family'] != 'Alpine'

- name: (Debian/Ubuntu) Add NGINX signing key
  ansible.builtin.get_url:
    url: "{{ keysite }}"
    dest: /usr/share/keyrings/nginx-archive-keyring.gpg
    checksum: sha256:55385da31d198fa6a5012d40ae98ecb272a6c4e8fffffba94719ffd3e87de37a
  when: ansible_facts['os_family'] == 'Debian'

- name: (Red Hat/SLES OSs) Add NGINX signing key
  ansible.builtin.rpm_key:
    fingerprint: 8540A6F18833A80E9C1653A42FD21310B49F6B46
    key: "{{ keysite }}"
  when: ansible_facts['os_family'] in ['RedHat', 'Suse']
